python3 -m pytest  ./tests/hw1 -v -k "forward"
python3 -m pytest  ./tests/hw1 -v -k "backward"
python3 -m pytest  ./tests/hw1 -v -k "topo_sort"
python3 -m pytest  ./tests/hw1 -v -k "compute_gradient"
python3 -m pytest ./tests/hw1 -k "softmax_loss_ndl"
python3 -m pytest ./tests/hw1 -l -k "nn_epoch_ndl"
